### ISSUE TITLE
Installation instructions miss dependencies

### ISSUE THREAD

**Issue by ZiZ1** [pagnani/PlmDCA#10]
When  I tried to install PlmDCA on a clean installation of Julia 1.4 according to the instructions in the README.md, I got the following error: 
"
ERROR: Unsatisfiable requirements detected for package GaussDCA [bc09176e]:
 GaussDCA [bc09176e] log:
 ├─GaussDCA [bc09176e] has no known versions!
 └─restricted to versions * by PlmDCA [06784e46] — no versions left
   └─PlmDCA [06784e46] log:
     ├─possible versions are: 0.1.0 or uninstalled
     └─PlmDCA [06784e46] is fixed to version 0.1.0
"
The problem was fixed by installing GaussDCA. It would be helpful to add the dependencies to the README.

**Comment by pagnani** [comment]
Going to finally register the package. Closing
